name: AnyTimeCrafting
main: io.github.maple8192.anytimecrafting.AnyTimeCrafting
version: '${version}'
description: 作業台を設置しなくても使えるようにするプラグインです。
api-version: 1.18
depend: [ KotlinPluginLib ]
authors: [ Maple8192 ]
